spring:
  data:
    mongodb:
      authentication-database: admin
      username: josee1
      password: josee1
      host: localhost
      port: 27017
      database: customer
    #      uri: mongodb://josee1:josee1@localhost:27017/customer?authSource=admin


server:
  port: 8090